const ERROR_MESSAGES = {
  UPLOAD_FILE_MANDATORY: 'UPLOAD_FILE_MANDATORY',
  UPLOAD_USERID_MANDATORY: 'UPLOAD_USERID_MANDATORY',
  UPLOAD_FILE_EXCEEDEDMAXIMUMFILESIZE: 'UPLOAD_FILE_EXCEEDEDMAXIMUMFILESIZE',
};

module.exports = { ERROR_MESSAGES };
